# Generated by Django 5.2.7 on 2025-10-23 21:02

import django.db.models.deletion
import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettransaction'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(default=wallet.models.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('trading', 'Trading')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
