# Generated by Django 5.2.7 on 2025-10-19 14:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profit_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.85'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='robots/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('available_for_demo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martingale_multiplier', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='trading.markettype')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('buy', 'Buy/Rise/Touch'), ('sell', 'Sell/Fall/No Touch')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_win', models.BooleanField()),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_martingale', models.BooleanField(default=False)),
                ('martingale_level', models.PositiveIntegerField(default=0)),
                ('session_profit_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_demo', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='accounts.account')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.market')),
                ('used_robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.tradetype')),
            ],
        ),
        migrations.CreateModel(
            name='UserRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_robots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'robot')},
            },
        ),
    ]
