# Generated by Django 5.2.7 on 2025-10-19 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_userrobot_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrobot',
            unique_together={('user', 'robot')},
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.RemoveField(
            model_name='userrobot',
            name='account_type',
        ),
    ]
