# Generated by Django 5.2.7 on 2025-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_userrobot_unique_together_delete_pricehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='entry_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exit_spot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
