# Generated by Django 5.2.7 on 2025-10-20 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_current_spot_trade_entry_spot_trade_exit_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='win_rate',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
