# Generated by Django 5.2.7 on 2025-10-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_marketchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketChatMessage',
        ),
    ]
