# Generated by Django 5.2.7 on 2025-10-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrobot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrobot',
            name='account_type',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userrobot',
            unique_together={('user', 'robot', 'account_type')},
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='trading.market')),
            ],
        ),
    ]
